name: Publish Package to npmjs

on:
  push:
    branches:
      - main 
      

jobs:
  npm-build-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      # required - sets up auth in the node env
      - name: Set up Node.js
        uses: actions/setup-node@master
        with:
          node-version: 16.x
          registry-url: 'https://npm.pkg.github.com'
      # required
      - name: version & publish
        uses: geeman201/conventional-changelog-npm-publish/@v14
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
