name: Publish Package to npmjs

on:
  push:
    branches:
      - main 
      

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org/'
      - name: Install dependencies and build 🔧
        run: npm i && npm run build 
          
      - name: Patch Release tag
        if: ${{ contains( github.event.pull_request.labels.*.name, 'patch') }}
        run: npm version patch

      - name: Minor Release tag
        if: ${{ contains( github.event.pull_request.labels.*.name, 'minor') }}
        run: npm version minor

      - name: Major Release tag
        if: ${{ contains( github.event.pull_request.labels.*.name, 'major') }}
        run: npm version major
        
      - name: Publish package on NPM 📦
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
