name: Publish Package to npmjs

on:
  push:
    branches:
      - main


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@3
      - name: Install dependencies
        run: npm i
      - name: Run build
        run: npm run build
      - name: semantic release
        uses: cycjimmy/semantic-release-action@v3
        with:
          semantic_version: 19.0.5
          # Define all extra plugins used in .releaserc.yml
          # https://github.com/cycjimmy/semantic-release-action#extra_plugins
          extra_plugins: |
            @semantic-release/exec
            @semantic-release/changelog
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}