name: Publish Package to npmjs

on:
  push:
    branches:
      - main 
      

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 16
      uses: actions/setup-node@v1
      with:
        # specify node version and the registry for the RELEASE build
        node-version: 16
        registry-url: https://registry.npmjs.org/
    - name: npm ci, publish
      run: |
        npm ci
        NODE_ENV=production npm publish --access public
      env:
        # Add to github settings/secrets
        NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
