name: Publish Package to npmjs

on:
  push:
    branches:
      - main 
      

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org/'
      - name: Install dependencies and build 🔧
        run: npm i && npm run build 
      - name: Echo TOKEN
        run: echo "$TEST" && echo "end"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          TEST: ${{ secrets.TEST }}
      - name: Publish package on NPM 📦
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
